name: PR Build Check and Firebase Deployment

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Build the project
        run: yarn build

      # - name: Set up Java for Firebase Emulators
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: "adopt"
      #     java-version: "11"

      # - name: Cache Firebase Emulators
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/firebase/emulators
      #     key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}

      # - name: Run Tests
      #   run: yarn test
      #   env:
      #     FIREBASE_DEBUG_MODE: true
      #     FUNCTIONS_EMULATOR: true

      - name: Set up Firebase authentication
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > gcloud.json
          echo $HOME
          echo $GITHUB_WORKSPACE
          cat gcloud.json

      - name: Deploy Firebase Rules
        run: npx firebase-tools deploy --only firestore:rules --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcloud.json

      - name: Deploy Firebase Indexes
        run: npx firebase-tools deploy --only firestore:indexes --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcloud.json

      - name: Deploy Firebase Functions
        run: npx firebase-tools deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcloud.json
