name: PR Build Check and Firebase Deployment

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Build the project
        run: yarn build

      - name: Set up Java for Firebase Emulators
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Cache Firebase Emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}

      - name: Run Tests
        run: yarn test
        env:
          FIREBASE_DEBUG_MODE: true
          FUNCTIONS_EMULATOR: true

      - name: Set up Firebase authentication
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/firebase-service-account.json
          firebase use ourlib-76289
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-service-account.json

      - name: Deploy Firebase Rules
        run: firebase deploy --only firestore:rules

      - name: Deploy Firebase Indexes
        run: firebase deploy --only firestore:indexes

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
